# Generated by Django 5.2.15 on 2026-06-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecitationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('voice', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('audio_base64', models.TextField()),
                ('duration', models.FloatField()),
                ('text_length', models.IntegerField()),
                ('prompt_used', models.TextField()),
                ('elapsed_time_ms', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('candidates_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
