# Generated by Django 5.2.15 on 2026-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recitationhistory',
            name='chunk_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='recitationhistory',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
