# Generated by Django 5.2.15 on 2026-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_recitationhistory_chunk_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(default='official', max_length=20)),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('new_api_base_url', models.CharField(default='http://192.168.100.170:3000/v1', max_length=255)),
                ('new_api_key', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'API Settings',
            },
        ),
    ]
