# Generated by Django 5.2.15 on 2026-06-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_apisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='model_name',
            field=models.CharField(default='gemini-3.1-flash-tts', max_length=100),
        ),
    ]
